#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Nov 12 08:16:24 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7390c4cef8db470ba3125d5d04a63a84 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RSA_accelerator_tb_behav xil_defaultlib.RSA_accelerator_tb -log elaborate.log"
xelab -wto 7390c4cef8db470ba3125d5d04a63a84 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RSA_accelerator_tb_behav xil_defaultlib.RSA_accelerator_tb -log elaborate.log

