# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/rsa_soc_axi_smc_0.xci
# IP: The module: 'rsa_soc_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/bd_ae75.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/rsa_soc_axi_smc_0.xci
# IP: The module: 'rsa_soc_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/bd_ae75.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020/RSA_soc/boards/ip/rsa_soc_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rsa_soc_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
