#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 17 14:27:11 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6776c0d0857846298ec0e69f9af59c9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RL_exp_tb_behav xil_defaultlib.RL_exp_tb -log elaborate.log"
xelab -wto 6776c0d0857846298ec0e69f9af59c9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot RL_exp_tb_behav xil_defaultlib.RL_exp_tb -log elaborate.log

