webtalk_init -webtalk_dir /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020_quad_core/RSA_accelerator/RSA_accelerator/RSA_accelerator.sim/sim_1/behav/xsim/xsim.dir/RSA_accelerator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 17 16:49:22 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b23c8356-a75c-4c2c-b7b1-b751a49d01c2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e2b24d0d83ed48ed8ec0f83ca17f0f3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.03 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1751.433 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3442872 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2520.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122516_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1025651164 -regid "" -xml /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020_quad_core/RSA_accelerator/RSA_accelerator/RSA_accelerator.sim/sim_1/behav/xsim/xsim.dir/RSA_accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020_quad_core/RSA_accelerator/RSA_accelerator/RSA_accelerator.sim/sim_1/behav/xsim/xsim.dir/RSA_accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/aleksw/NTNU/First_Year/DDS/Project/tfe4141_rsa_integration_kit_2020_quad_core/RSA_accelerator/RSA_accelerator/RSA_accelerator.sim/sim_1/behav/xsim/xsim.dir/RSA_accelerator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
