#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 17 17:47:15 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 05eae9ff11a24f01bbce43035f6d4ea8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot csa_mult_tb_behav xil_defaultlib.csa_mult_tb -log elaborate.log"
xelab -wto 05eae9ff11a24f01bbce43035f6d4ea8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot csa_mult_tb_behav xil_defaultlib.csa_mult_tb -log elaborate.log

